# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - 0.6
notifications:
  email: false
branches:
  only:
  - master
  - /release-.*/
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone("https://github.com/JuliaComputing/IndexedTables.jl.git")'
  - julia -e 'Pkg.add("SimpleTraits"); Pkg.checkout("SimpleTraits")'
  - julia -e 'Pkg.add("StatsModels"); Pkg.checkout("StatsModels")'
  - julia -e 'Pkg.clone(pwd()); Pkg.build("IterableTables"); Pkg.test("IterableTables"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("IterableTables")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("IterableTables")); include(joinpath("docs", "make.jl"))'
  